- name: variables
  hosts: localhost
  vars:
    URL: sample.com
  tasks: 
    - name: print URL vraible
      ansible.builtin.debug:
         msg: "{{ URL }}"  

- name: variables
  hosts: localhost
  vars:
    URL1: example.com
    URL2: example.com
  tasks: 
    - name: print URL vraible
      ansible.builtin.debug:
         msg: "{{ URL1 }}"           
      vars:
          URL: sample.com
    - name: print URL vraible
      ansible.builtin.debug:
         msg: "{{ URL2 }}"           
      vars:
          URL2: sample.com    
- name: register the varaible
  hosts: localhost
  tasks:
    - name: get the uptime
      ansible.builtin.shell: uptime
      register: uptime_output
    - name: print the uptime
      ansible.builtin.debug:
        msg: "{{ uptime_output }}"              

